name: Build EXE

on:
  workflow_dispatch:  # botón "Run workflow" manual en la pestaña Actions

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: >
          pyinstaller --onefile --windowed
          Existencia_Textos.py

      - run: >
          pyinstaller --onefile --windowed
          --icon=Icono.ico
          --add-data "Icono.ico;."
          --add-data "Icono.png;."
          --add-data "Firmas;Firmas"
          Existencia_Textos.py

      - uses: actions/upload-artifact@v4
        with:
          name: StockControl-exe
          path: dist/*.exe
